# Generated by Django 2.1.5 on 2020-02-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20200209_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_name', to='department.Department'),
        ),
    ]
