# Generated by Django 2.1.5 on 2020-02-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20200210_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile',
            field=models.URLField(null=True, unique=True),
        ),
    ]
